### ISSUE TITLE
ImportError on tutorial

### ISSUE THREAD

**Issue by ksk-jij** [NVIDIA/cuda-quantum#3025]
### Required prerequisites

- [x] Consult the [security policy](https://github.com/NVIDIA/cuda-quantum/security/policy). If reporting a security vulnerability, do not report the bug using this form. Use the process described in the policy to report the issue.
- [x] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [x] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

There is an import error on the tutorial https://nvidia.github.io/cuda-quantum/latest/using/examples/dynamics_examples.html#cavity-qed.

### Steps to reproduce the bug

Running the code
`
from cudaq import boson
`

returns  the following error.
`
ImportError: cannot import name 'boson' from 'cudaq' (/opt/nvidia/cudaq/cudaq/__init__.py)
`

### Expected behavior

No error arises.

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA-Q version**: cu12-0.10.0
- **Python version**: 3.10.12
- **C++ compiler**: N/A
- **Operating system**: Linux (CUDA-Q 12 latest docker image as of 9/June/2025)

**Comment by bebora** [comment]
Hi @ksk-jij, the mentioned example works on CUDA-Q 0.11.0. That boson import was introduced in #2817, which landed in release 0.11.0. I suggest using a more recent container (i.e. `cu12-0.11.0`).

**Comment by sacpis** [comment]
Fixing it. Will check other examples as well.

**Comment by sacpis** [comment]
Thanks @bebora. This is available with the latest container.

**Comment by sacpis** [comment]
@ksk-jij  Can we close this issue if it is working for you with the latest image?

**Comment by ksk-jij** [comment]
@bebora @sacpis Thank you for your swift answers :) It is working for me with the latest image! I'll close this issue! Thanks again!
